In [1]:
import pandas as pd
import matplotlib.pyplot as plt


depression_us=pd.read_csv("../data/depression_us.csv")

In [2]:


multi_cols=['education', 'urban', 'gender', 'religion', 'orientation',
       'race', 'married']


#Duplicating columns for multi value columns
depression_us = pd.get_dummies(data = depression_us, columns = multi_cols)

In [3]:
depression_us.drop('Condition',axis=1,inplace=True)

In [4]:
depression_us

,Unnamed: 0,TIPI1,TIPI2,TIPI3,TIPI4,TIPI5,TIPI6,TIPI7,TIPI8,TIPI9,...,race_20,race_30,race_40,race_50,race_60,race_70,married_0,married_1,married_2,married_3
0,1,6,5,4,7,5,4,7,7,1,...,0,0,0,0,0,1,0,1,0,0
1,3,1,1,7,4,6,4,6,1,6,...,0,0,0,0,0,1,0,1,0,0
2,5,2,1,6,1,7,7,7,2,6,...,0,0,0,0,0,1,0,1,0,0
3,8,1,4,5,7,5,7,6,7,1,...,0,0,0,0,0,1,0,1,0,0
4,10,5,3,6,6,3,4,4,7,5,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8199,39766,4,1,7,7,7,7,7,1,1,...,0,0,0,0,0,1,0,1,0,0
8200,39768,6,5,6,7,6,4,6,5,5,...,0,0,0,0,1,0,0,1,0,0
8201,39769,6,5,4,5,6,3,5,2,5,...,0,0,0,0,0,1,0,1,0,0
8202,39772,6,6,7,5,6,3,6,1,5,...,0,1,0,0,0,0,0,0,1,0
8203,39773,1,6,5,7,3,5,3,5,3,...,0,0,0,0,1,0,0,1,0,0

In [5]:
depression_us=depression_us.drop(depression_us.columns[0], axis=1)

In [6]:
depression_targets=depression_us['target']
depression_targets=depression_targets.astype('category')
depression_us.drop('target',axis=1,inplace=True)

In [7]:
depression_us['age']-=depression_us['age'].mean()
depression_us['age']/=depression_us['age'].std()

In [8]:
depression_us['familysize']-=depression_us['familysize'].mean()
depression_us['familysize']/=depression_us['familysize'].std()

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Ridge, Lasso, LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor, BaggingRegressor, RandomForestRegressor, StackingRegressor
from xgboost import XGBRegressor
# from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(depression_us,depression_targets, test_size=0.25)

In [19]:
lr = LogisticRegression(multi_class='multinomial')
pred_lr = lr.fit(X_train[['TIPI3','TIPI4','TIPI6','TIPI8','TIPI9']], y_train).predict(X_test[['TIPI3','TIPI4','TIPI6','TIPI8','TIPI9']])

# Checking Model Metrics
# from sklearn.metrics import r2_score, mean_squared_error
# print("R2 Score: ", r2_score(y_test, pred_lr))
# print("RMSE: ", np.sqrt(mean_squared_error(y_test, pred_lr)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [20]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.49      0.86      0.62       779
           1       0.00      0.00      0.00       181
           2       0.33      0.00      0.01       327
           3       0.44      0.67      0.53       440
           4       0.00      0.00      0.00       324

    accuracy                           0.47      2051
   macro avg       0.25      0.31      0.23      2051
weighted avg       0.33      0.47      0.35      2051

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [17]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(splitter='best')

pred_dt = dt.fit(X_train[['TIPI3','TIPI4','TIPI6','TIPI8','TIPI9']], y_train).predict(X_test[['TIPI3','TIPI4','TIPI6','TIPI8','TIPI9']])

In [18]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

           0       0.48      0.62      0.54       779
           1       0.11      0.12      0.11       181
           2       0.18      0.17      0.18       327
           3       0.42      0.34      0.37       440
           4       0.14      0.09      0.11       324

    accuracy                           0.36      2051
   macro avg       0.27      0.27      0.26      2051
weighted avg       0.33      0.36      0.34      2051