In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
# import altair as alt

depression=pd.read_csv("../data/depression_overall.csv")

In [5]:
depression=depression.drop(depression.columns[0], axis=1)
depression.head()

,TIPI1,TIPI2,TIPI3,TIPI4,TIPI5,TIPI6,TIPI7,TIPI8,TIPI9,TIPI10,...,gender,age,religion,orientation,race,married,familysize,VCL,Condition,target
0,1,5,7,7,7,7,7,5,1,1,...,2,16,12,1,10,1,2,8,Severe,4
1,6,5,4,7,5,4,7,7,1,5,...,2,16,7,0,70,1,4,8,Severe,4
2,2,5,2,2,5,6,5,5,3,2,...,2,17,4,3,60,1,3,7,Extremely Severe,0
3,1,1,7,4,6,4,6,1,6,1,...,2,13,4,5,70,1,5,7,Moderate,2
4,2,5,3,6,5,5,5,6,3,3,...,2,19,10,1,10,1,4,10,Extremely Severe,0

In [6]:
depression.columns

Index(['TIPI1', 'TIPI2', 'TIPI3', 'TIPI4', 'TIPI5', 'TIPI6', 'TIPI7', 'TIPI8',
       'TIPI9', 'TIPI10', 'education', 'urban', 'gender', 'age', 'religion',
       'orientation', 'race', 'married', 'familysize', 'VCL', 'Condition',
       'target'],
      dtype='object')

In [8]:
import altair

ModuleNotFoundError: No module named 'altair'

In [9]:
depression['AgeBand'] = pd.cut(depression['age'], 4)
depression[['AgeBand','target']].groupby(['AgeBand'], as_index=False).mean().sort_values(by='AgeBand', ascending=True)
# Changing names of columns to remove ',' and brackets
#depression['AgeBand'].replace({'(12.924, 32.0]': 'AgeBand_1','(32.0, 51.0]':'AgeBand_2',
                           # '(51.0, 70.0]':'AgeBand_3','(70.0, 89.0]':'AgeBand_4'}, inplace=True,columns = None)

# Combining target categories
depression['target'] = np.where(
     depression['target'].between(-1, 3, inclusive=False), 0, 1)

/var/folders/pm/h5r7gpgs4n9g04t9cxlhxj500000gn/T/ipykernel_99323/3318273055.py:9: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  depression['target'].between(-1, 3, inclusive=False), 0, 1)

In [10]:
depression_plot = depression.drop(['TIPI1', 'TIPI2', 'TIPI3', 'TIPI4', 'TIPI5', 'TIPI6', 'TIPI7', 'TIPI8',
       'TIPI9', 'TIPI10','Condition','age','VCL'],axis=1,inplace=False)

In [11]:
depression_plot

,education,urban,gender,religion,orientation,race,married,familysize,target,AgeBand
0,2,3,2,12,1,10,1,2,1,"(12.924, 32.0]"
1,2,3,2,7,0,70,1,4,1,"(12.924, 32.0]"
2,2,3,2,4,3,60,1,3,0,"(12.924, 32.0]"
3,1,3,2,4,5,70,1,5,0,"(12.924, 32.0]"
4,3,2,2,10,1,10,1,4,0,"(12.924, 32.0]"
...,...,...,...,...,...,...,...,...,...,...
39758,2,2,1,2,4,60,1,2,0,"(12.924, 32.0]"
39759,3,2,1,10,0,10,1,4,0,"(12.924, 32.0]"
39760,3,2,2,7,1,30,2,3,1,"(32.0, 51.0]"
39761,3,2,2,6,1,60,1,2,0,"(12.924, 32.0]"
39762,3,3,2,10,1,10,1,4,1,"(12.924, 32.0]"

In [12]:
depression_plot.columns

Index(['education', 'urban', 'gender', 'religion', 'orientation', 'race',
       'married', 'familysize', 'target', 'AgeBand'],
      dtype='object')

In [13]:
try_data = depression_plot.melt(id_vars='target',value_vars = ['education', 'urban', 'gender', 'religion', 'orientation', 'race',
       'married', 'familysize', 'AgeBand'], var_name = 'demo', value_name='label')

In [14]:
try_data = try_data.astype({'target': 'str', 'demo': 'str','label':'str'})

In [15]:
fig_data = (try_data.groupby(['target','demo',"label"]).size()).to_frame().reset_index()
fig_data.columns = ["target","demo","label","count"]
fig_data

    target       demo           label  count
0        0    AgeBand  (12.924, 32.0]  22179
1        0    AgeBand    (32.0, 51.0]   1786
2        0    AgeBand    (51.0, 70.0]    442
3        0    AgeBand    (70.0, 89.0]     26
4        0  education               0    330
..     ...        ...             ...    ...
130      1   religion               9     64
131      1      urban               0    131
132      1      urban               1   3235
133      1      urban               2   5200
134      1      urban               3   6764

[135 rows x 4 columns]

In [16]:
#Religion Rename
fig_data.loc[(fig_data.label == '0') & (fig_data.demo == 'religion'),'label_var']='Did not wish to answer'
fig_data.loc[(fig_data.label == '1') & (fig_data.demo == 'religion'),'label_var']='Agnostic'
fig_data.loc[(fig_data.label == '2') & (fig_data.demo == 'religion'),'label_var']='Atheist'
fig_data.loc[(fig_data.label == '3') & (fig_data.demo == 'religion'),'label_var']='Buddhist'
fig_data.loc[(fig_data.label == '4') & (fig_data.demo == 'religion'),'label_var']='Christian (Catholic)'
fig_data.loc[(fig_data.label == '5') & (fig_data.demo == 'religion'),'label_var']='Christian (Mormon)'
fig_data.loc[(fig_data.label == '6') & (fig_data.demo == 'religion'),'label_var']='Christian (Protestant)'
fig_data.loc[(fig_data.label == '7') & (fig_data.demo == 'religion'),'label_var']='Christian (Other)'
fig_data.loc[(fig_data.label == '8') & (fig_data.demo == 'religion'),'label_var']='Hindu'
fig_data.loc[(fig_data.label == '9') & (fig_data.demo == 'religion'),'label_var']='Jewish'
fig_data.loc[(fig_data.label == '10') & (fig_data.demo == 'religion'),'label_var']='Muslim'
fig_data.loc[(fig_data.label == '11') & (fig_data.demo == 'religion'),'label_var']='Sikh'
fig_data.loc[(fig_data.label == '12') & (fig_data.demo == 'religion'),'label_var']='Other'

In [17]:
#Race Rename
fig_data.loc[(fig_data.label == '10') & (fig_data.demo == 'race'),'label_var']='Asian'
fig_data.loc[(fig_data.label == '20') & (fig_data.demo == 'race'),'label_var']='Arab'
fig_data.loc[(fig_data.label == '30') & (fig_data.demo == 'race'),'label_var']='Black'
fig_data.loc[(fig_data.label == '40') & (fig_data.demo == 'race'),'label_var']='Indigenous Australian'
fig_data.loc[(fig_data.label == '50') & (fig_data.demo == 'race'),'label_var']='Native American'
fig_data.loc[(fig_data.label == '60') & (fig_data.demo == 'race'),'label_var']='White'
fig_data.loc[(fig_data.label == '70') & (fig_data.demo == 'race'),'label_var']='Other'

In [18]:
#Orientation Rename
fig_data.loc[(fig_data.label == '0') & (fig_data.demo == 'orientation'),'label_var']='Did not wish to answer'
fig_data.loc[(fig_data.label == '1') & (fig_data.demo == 'orientation'),'label_var']='Heterosexual'
fig_data.loc[(fig_data.label == '2') & (fig_data.demo == 'orientation'),'label_var']='Bisexual'
fig_data.loc[(fig_data.label == '3') & (fig_data.demo == 'orientation'),'label_var']='Homosexual'
fig_data.loc[(fig_data.label == '4') & (fig_data.demo == 'orientation'),'label_var']='Asexual'
fig_data.loc[(fig_data.label == '5') & (fig_data.demo == 'orientation'),'label_var']='Other'

In [19]:
#Education Rename
fig_data.loc[(fig_data.label == '0') & (fig_data.demo == 'education'),'label_var']='Did not wish to answer'
fig_data.loc[(fig_data.label == '1') & (fig_data.demo == 'education'),'label_var']='Less than high school'
fig_data.loc[(fig_data.label == '2') & (fig_data.demo == 'education'),'label_var']='High school'
fig_data.loc[(fig_data.label == '3') & (fig_data.demo == 'education'),'label_var']='University degree'
fig_data.loc[(fig_data.label == '4') & (fig_data.demo == 'education'),'label_var']='Graduate degree'

In [20]:
#Age Rename
fig_data.loc[(fig_data.label == '(12.924, 32.0]') & (fig_data.demo == 'AgeBand'),'label_var']='13-32 Years'
fig_data.loc[(fig_data.label == '(32.0, 51.0]') & (fig_data.demo == 'AgeBand'),'label_var']='32-51 Years'
fig_data.loc[(fig_data.label == '(51.0, 70.0]') & (fig_data.demo == 'AgeBand'),'label_var']='51-70 Years'
fig_data.loc[(fig_data.label == '(70.0, 89.0]') & (fig_data.demo == 'AgeBand'),'label_var']='70-89 Years'

In [21]:
#Gender Rename
fig_data.loc[(fig_data.label == '0') & (fig_data.demo == 'gender'),'label_var']='Did not wish to answer'
fig_data.loc[(fig_data.label == '1') & (fig_data.demo == 'gender'),'label_var']='Male'
fig_data.loc[(fig_data.label == '2') & (fig_data.demo == 'gender'),'label_var']='Female'
fig_data.loc[(fig_data.label == '3') & (fig_data.demo == 'gender'),'label_var']='Other'

In [22]:
#Married Rename
fig_data.loc[(fig_data.label == '0') & (fig_data.demo == 'married'),'label_var']='Did not wish to answer'
fig_data.loc[(fig_data.label == '1') & (fig_data.demo == 'married'),'label_var']='Never married'
fig_data.loc[(fig_data.label == '2') & (fig_data.demo == 'married'),'label_var']='Currently married'
fig_data.loc[(fig_data.label == '3') & (fig_data.demo == 'married'),'label_var']='Previously married'

In [23]:
#Urban Rename
fig_data.loc[(fig_data.label == '0') & (fig_data.demo == 'urban'),'label_var']='Did not wish to answer'
fig_data.loc[(fig_data.label == '1') & (fig_data.demo == 'urban'),'label_var']='Rural (country side)'
fig_data.loc[(fig_data.label == '2') & (fig_data.demo == 'urban'),'label_var']='Suburban'
fig_data.loc[(fig_data.label == '3') & (fig_data.demo == 'urban'),'label_var']='Urban (town, city)'

In [24]:
fig_data.to_csv('fig_data.csv',index=False)

In [30]:
selection = alt.selection_multi(fields=['demo','label_var'])
click = alt.selection_multi()
color = color=alt.Color(
            "count", scale=alt.Scale(scheme="redyellowblue"), legend=None,
        )

hist1 = alt.Chart(fig_data).mark_bar().encode(
    x='demo',
    y='count',
    color=alt.condition(selection, 'label_var', alt.value('grey'),scale=alt.Scale(scheme=""),
            legend=None),
    tooltip=[
            alt.Tooltip("demo", title="demo"),
            alt.Tooltip("count", title="count"),
            alt.Tooltip("label_var", title="label_var")],
).add_selection(
     selection
).properties(width=300, height=300)
hist1

NameError: name 'alt' is not defined

In [115]:
hist2 = alt.Chart(fig_data).mark_bar().encode(
    x='count',
    y='target',
    color = alt.Color('label_var',scale=alt.Scale(scheme="yellowgreenblue"),legend=None),
    tooltip=[alt.Tooltip("target", title="target"),
            alt.Tooltip("label_var", title="label_var"),
            alt.Tooltip("demo", title="demo")]  
).add_selection(
     selection
 ).transform_filter(
   selection
).properties(width=400, height=100)
hist2

alt.Chart(...)

In [116]:
total_participation_viz=alt.vconcat(hist1, hist2).properties(
    title={
      "text": ["Which Demographic by Label has the most count?"], 
      "subtitle": ["Click to see Count of Demographic by Depression Target"],
      "subtitleFontSize":13,
      'subtitleFontStyle':'italic',
      "color": "black",
      "subtitleColor": "black"
    }
).configure(background='#E7E6E1')
total_participation_viz

alt.VConcatChart(...)

In [34]:
import gzip
f_in = open('../StackedPickle.pkl')
f_out = gzip.open('../StackedPickle.pkl.gz', 'wb')
f_out.writelines(f_in)
f_out.close()
f_in.close()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte